version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /usr/app/node-modules
            - ./server:/usr/app
