apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: wokrer
  template:
    metadata:
      labels:
        component: wokrer
    spec:
      containers:
      - name: wokrer
        image: srinivra/multi-worker
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"